export const RhineCafeJP = "ラインカフェー";
export const AlterLinkJP: string[] = ["自己紹介", "経験", "プロジェクト", "教育"];
export const UsernameJP: string = "萧楚劼";
export const DownloadResumeJP: string = "履歴書をダウンロード";
export const BioDescriptionJP: string = `初めまして、萧楚劼（そかつ）とおもします。僕はソフトウェアエンジニアとなりたい夢を持っています。 特にAIと機器学習の技術もっと知りたいのです。その夢を叶うために一緒に一生懸命頑張りましょう。`
export const FrameworksJP: string = "フレームワーク";
export const ToolsJP: string = "ツール";
export const EducationJP: string = "教育";
export const SpokenLanguageJP: string = "話せる言語";
export const ComputerLanguageJP: string = "プログラミング言語";
export const ExperienceJP: string = "経験";
